import type { Metadata } from 'next';
import { Inter, Manrope } from 'next/font/google';
import './globals.css';
import TanStackProvider from '@/components/providers/TanStackProvider/TanStackProvider';
import { Toaster } from 'react-hot-toast';
import Header from '@/components/layout/Header/Header';

const manrope = Manrope({
  variable: '--font-family',
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600', '700'],
});

const inter = Inter({
  variable: '--second-family',
  subsets: ['latin', 'cyrillic'],
  weight: ['500'],
});

export const metadata: Metadata = {
  title: 'Rental Car',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${manrope.variable} ${inter.variable} h-full antialiased`}
    >
      <body className=' bg-(--bg) [font-family:var(--font-family)]'>
        <TanStackProvider>
          <Header />
          {children}
          <Toaster />
        </TanStackProvider>
      </body>
    </html>
  );
}
